### ISSUE TITLE
get menu failed!

### ISSUE THREAD

**Issue by q640202047** [Panfen/wemovie#4]
我的公众号是新的公众号，没有配置菜单
当发送文字消息给公众号时，node服务端报错如下：

`
Error: get menu failed!
      at E:\hbuilder_workspace\wemovie\wechat\wechat.js:244:12
      at tryCatcher (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\rele
ase\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\hbuilder_workspace\wemovie\node_m
odules\bluebird\js\release\promise.js:512:31)
      at Promise._settlePromise (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\r
elease\promise.js:569:18)
      at Promise._settlePromise0 (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\
release\promise.js:614:10)
      at Promise._settlePromises (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\
release\promise.js:693:18)
      at Promise._fulfill (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\release
\promise.js:638:18)
      at Request._callback (E:\hbuilder_workspace\wemovie\node_modules\bluebird\js\releas
e\nodeback.js:42:21)
      at Request.self.callback (E:\hbuilder_workspace\wemovie\node_modules\request\reques
t.js:188:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (E:\hbuilder_workspace\wemovie\node_modules\request\request.
js:1171:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (E:\hbuilder_workspace\wemovie\node_modules\request\
request.js:1091:12)
      at Object.onceWrapper (events.js:313:30)
`

**Comment by RaidenCJ** [comment]
@q640202047 
请问这个问题你那解决了吗?是因为微信平台设置菜单反应比较慢的原因么?
