### ISSUE TITLE
有报错,能看看什么原因吗?

### ISSUE THREAD

**Issue by RaidenCJ** [Panfen/wemovie#6]
Listening 80...
oFYSY1BaQHaE2BBWeJFW59EeZbcE 悄悄地走了...

  TypeError: Cannot read property 'then' of undefined
      at /home/git/weixin_djss/wechat/wechat.js:237:26
      at Promise._execute (/home/git/weixin_djss/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/home/git/weixin_djss/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (/home/git/weixin_djss/node_modules/bluebird/js/release/promise.js:79:10)
      at Wechat.getMenu (/home/git/weixin_djss/wechat/wechat.js:236:9)
      at Object.exports.setMenu (/home/git/weixin_djss/weixin.js:158:33)
      at next (native)
      at onFulfilled (/home/git/weixin_djss/node_modules/co/index.js:65:19)
      at /home/git/weixin_djss/node_modules/co/index.js:54:5
      at Object.co (/home/git/weixin_djss/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/git/weixin_djss/node_modules/co/index.js:118:63)
      at next (/home/git/weixin_djss/node_modules/co/index.js:99:29)
      at onFulfilled (/home/git/weixin_djss/node_modules/co/index.js:69:7)
      at /home/git/weixin_djss/node_modules/co/index.js:54:5
      at Object.co (/home/git/weixin_djss/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/git/weixin_djss/node_modules/co/index.js:118:63)

**Comment by yiluxiangbei87110** [comment]
加个return
